name: Create minor tag

on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - name: Get current version from composer.json
        run: |
          echo "current_version=$(grep -m1 version composer.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $GITHUB_ENV
      - name: Bump a new minor version
        run: |
          echo "new_version=$(echo ${{env.current_version}} | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')" >> $GITHUB_ENV
      - name: Show new value
        run: |
          echo "Bumping version from ${{ env.current_version }} to ${{ env.new_version }}"
      - name: Update composer.json with new version
        run: |
          # Replace the version number in composer.json
          sed -i "s/${{ env.current_version }}/${{ env.new_version }}/g" composer.json
      - name: Commit the changes
        run: |
          # Add the modified composer.json file to the staging area
          git add composer.json
          # Commit the changes with a message
          git commit -m "Update composer.json to version ${{ env.new_version }}"
      - name: Create the tag
        run: |
          # Create the tag
          git tag ${{ env.new_version }}

          # Push the tag to GitHub
          git push origin ${{ env.new_version }}
