name: Create minor tag

on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.action_state }}" # This will output 'yellow'
      - name: Get the current version
        run: |
          # Extract the current version from composer.json
          echo ::set-env name=CURRENT_VERSION::$(grep -m1 version composer.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')
          echo $CURRENT_VERSION
          
          # Increment the patch version number
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          echo $NEW_VERSION
          
      - name: Update composer.json
        run: |
          # Replace the version number in composer.json
          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" composer.json

      - name: Set variable
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Echo variable
        run: echo ${{ steps.minor-tag.outputs.SELECTED_COLOR }}"
      - name: Commit the changes
        run: |
          # Add the modified composer.json file to the staging area
          git add composer.json

          # Commit the changes with a message
          git commit -m "Update composer.json to version $NEW_VERSION"

      - name: Create the tag
        run: |
          # Create the tag
          git tag $NEW_VERSION

          # Push the tag to GitHub
          git push origin $NEW_VERSION
