name: Create minor tag

on:
  push:
    branches:
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ls -la
      - name: Set the value
        id: step_one
        run: |
          echo "current_version=$(grep -m1 version composer.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')" >> $GITHUB_ENV
          echo "curw=$(date +%F)" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo "${{ env.current_version }}"
          echo "${{ env.curw }}"
      - name: Get the current version
        run: |
          echo "new_version=$(echo env.current_version | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')" >> $GITHUB_ENV
      - name: Use the value
        id: step_two2
        run: |
          echo "${{ env.new_version }}"
      - name: Update composer.json
        run: |
          # Replace the version number in composer.json
          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" composer.json

      - name: Set variable
        run: echo "SELECTED_COLOR=green" >> $GITHUB_OUTPUT
      - name: Echo variable
        run: echo ${{ steps.minor-tag.outputs.SELECTED_COLOR }}"
      - name: Commit the changes
        run: |
          # Add the modified composer.json file to the staging area
          git add composer.json

          # Commit the changes with a message
          git commit -m "Update composer.json to version $NEW_VERSION"

      - name: Create the tag
        run: |
          # Create the tag
          git tag $NEW_VERSION

          # Push the tag to GitHub
          git push origin $NEW_VERSION
