name: Create minor tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the current version
        run: |
          # Extract the current version from composer.json
          CURRENT_VERSION=$(grep -m1 version composer.json | awk -F: '{ print $2 }' | sed 's/[", ]//g')

          # Increment the patch version number
          NEW_VERSION=$(echo $CURRENT_VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
      - name: List files
        run: ls -la      
      - name: PWD
        run: $(pwd)      
      - name: list of parent
        run: ls -la ..    
      - name: list of parent parent
        run: ls -la ../..    
      - name: Echo File Path
        run: echo $(pwd)/composer.json
      - name: Install dependencies
        run: composer install
      - name: Run PHPUnit tests
        run: vendor/bin/phpunit
      - name: Update composer.json
        run: |
          # Replace the version number in composer.json
          sed -i "s/$CURRENT_VERSION/$NEW_VERSION/g" composer.json

      - name: Commit the changes
        run: |
          # Add the modified composer.json file to the staging area
          git add composer.json

          # Commit the changes with a message
          git commit -m "Update composer.json to version $NEW_VERSION"

      - name: Create the tag
        run: |
          # Create the tag
          git tag $NEW_VERSION

          # Push the tag to GitHub
          git push origin $NEW_VERSION
